# Generated by Django 5.0.4 on 2025-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('table', models.CharField(max_length=200, null=True)),
                ('review', models.CharField(max_length=200, null=True)),
                ('rate', models.FloatField()),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
