# Generated by Django 5.0.4 on 2025-09-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
