# Generated by Django 5.0.4 on 2025-09-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tabletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletype',
            name='name',
        ),
        migrations.AddField(
            model_name='tabletype',
            name='table_types',
            field=models.ManyToManyField(related_name='clubs', related_query_name='clubs', to='app.tabletype'),
        ),
    ]
