# Generated by Django 5.0.4 on 2025-09-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tabletype_name_tabletype_table_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletype',
            name='table_types',
        ),
        migrations.AddField(
            model_name='tabletype',
            name='name_table',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
