# Generated by Django 5.0.4 on 2025-09-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tabletype_table_types_tabletype_name_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
