# Generated by Django 5.0.4 on 2025-09-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_club_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
