# Generated by Django 5.0.4 on 2025-09-19 05:54

import clubs.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('type_district', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('table', models.CharField(max_length=200, null=True)),
                ('review', models.CharField(max_length=200, null=True)),
                ('rate', models.FloatField()),
                ('link', models.CharField(max_length=200, null=True)),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to=clubs.models.club_thumbnail_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
            ],
        ),
        migrations.CreateModel(
            name='TablesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_table', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clubs.models.club_slider_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club image',
                'verbose_name_plural': 'Club images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
