# Generated by Django 5.0.4 on 2025-09-26 06:20

import clubs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('type_district', models.CharField(choices=[('nội thành', 'Nội thành'), ('ngoại thành', 'Ngoại thành')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('price', models.CharField(blank=True, max_length=200)),
                ('table', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to=clubs.models.proposed_thumb_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
